---
title: "Conditional Models"
author: "Tom Zhang"
date: "11/29/2021"
output: html_document
---

## Imports

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(broom)
library(jsonlite)
library(igraph)

clash <- read_csv("sample/clash_sample_500k.csv", 
    col_types = cols(battleid = col_character(), 
        playertag = col_character(), battletime = col_datetime(format = "%Y-%m-%d %H:%M:%S"), 
        type = col_character(), isladdertournament = col_logical(), 
        arenaid = col_number(), arena = col_character(), 
        gamemodeid = col_number(), gamemode = col_character(), 
        deckselection = col_character(), 
        team = col_logical(), card = col_character(), 
        cardlevel = col_number(), clantag = col_character(), 
        startingtrophies = col_number(), 
        trophychange = col_number(), crowns = col_number(), 
        princesstower1hitpoints = col_number(), 
        princesstower2hitpoints = col_number(), 
        kingtowerhitpoints = col_number(), 
        boatbattleside = col_character(), 
        boatbattlewon = col_logical(), newboattowersdestroyed = col_number(), 
        prevboattowersdestroyed = col_number(), 
        remainingboattowers = col_number()))
```

## Subset

```{r}
clash <-
clash %>%
  slice(1:16004)  # use a small subset first: ~ 2000 decks
```

Slight issue: At some point, a few card names has been changed; now both copies are in the database.
* Fire Spirits -> Fire Spirit
* Heal -> Heal Spirit

```{r}
clash <-
clash %>%
  mutate(card = str_replace(card, "^Fire Spirits$", "Fire Spirit")) %>%
  mutate(card = str_replace(card, "^Heal$", "Heal Spirit"))
```

## Data Wrangling

```{r}
# a matrix of card indicators
x <- model.matrix(~0 + card + cardlevel, model.frame(~ ., clash, na.action=na.pass))

# clean up col names
colnames(x) <- str_remove_all(colnames(x), "card")
colnames(x) <- str_replace_all(colnames(x), " ", "_")
colnames(x) <- str_replace_all(colnames(x), "-", "_")

# save a copy of just card indicators
card_indicators <- x[, -ncol(x)]

# ignore levels for now

# # transform card levels into the same structure of card indicators
# card_levels = sweep(x[,-ncol(x)], MARGIN = 1, STATS = x[,ncol(x)], FUN = "*")
# 
# # make col names for card levels
# colnames(card_levels) = paste(colnames(card_levels),"_Level",sep = "")

# create names for all card and card interaction terms to be used later
interactions <- labels(terms(~ .^2, data = x[1:10, -ncol(x)]))

rm(x)  # free up memory

# put all columns together
cr <-
  # cbind(card_indicators, card_levels) %>%
  card_indicators %>%
  as_tibble() %>%
  mutate(battleid = clash$battleid,
         playertag = clash$playertag,
         battlewon = clash$trophychange) %>%
  group_by(battleid, playertag) %>%
  summarize_if(is.numeric, sum) %>%
  ungroup() %>%
  mutate(battlewon = if_else(battlewon >= 0 | is.na(battlewon), 1, 0))  # convert NA to 1

rm(clash)  # free up memory
rm(card_indicators)

cr
```

## Conditional Models

Subset the data to include only matches with a specified card, e.g., Royal Giant, and then fit the model with no interaction terms.

```{r}
# get card name columns
cards <- names(cr)[3:(ncol(cr) - 1)]

# a place to store coefficients of every conditional model
# card = main card, term = all other cards, estimate = coef; exclude intercept
all_mods <- tibble(card = NA, term = NA, estimate = NA)

for (i in 1:length(cards)) {
  card <- cards[i]
  
  # subset data
  sub <- filter(cr, !!as.symbol(card) == 1)
  
  # log-odds ~ with all other cards, no interactions
  f <- as.formula(paste("battlewon ~", paste(cards[! cards %in% card], collapse = " + ")))
  mod <- glm(f, data = sub, family = "binomial")
  
  tidy <-
    mod %>%
      tidy() %>%
      mutate(card = card) %>%
      select(card, term, estimate) %>%
      slice(-1)
  
  all_mods <- bind_rows(all_mods, tidy)
}

# keep only positive coefs
synergies <- 
  all_mods %>%
    filter(estimate > 15) %>%  # TODO find the optimal magnitude
    select(card, term)

# add back cards with no positive coefs
tmp <- tibble(card = cards, term = NA)
no_synergies <- anti_join(tmp, synergies, by = "card")  # get all cards not found in synergies df
synergies <- bind_rows(synergies, no_synergies)
```

# Save Graph to JSON

```{r}
json_df <-
synergies %>%
  group_by(card) %>%
  summarise(adjacent = list(term)) %>%
  ungroup() %>%
  column_to_rownames("card") %>%
  t() %>%
  as_tibble()

json <- toJSON(unbox(fromJSON(toJSON(json_df))))
json <- str_replace_all(json, "null", "")  # clean up [null]
```

```{r}
write(json, "graph_conditional.json")
```

# iGraph Cliques

```{r}
g <- graph_from_data_frame(synergies)
plot(g)
cliques(g, min = 8, max = 8)
```












